// Bag site interactivity (simple cart / search / filters)
let bagCart = []; const bagCartKey = 'bagCart';
function loadBagCart(){ const s = localStorage.getItem(bagCartKey); bagCart = s? JSON.parse(s):[]; updateBagCartCount(); }
function saveBagCart(){ localStorage.setItem(bagCartKey, JSON.stringify(bagCart)); }
function updateBagCartCount(){ const el = document.querySelector('.cart-count'); if(!el) return; const total = bagCart.reduce((s,i)=>s+i.quantity,0); el.textContent = total; el.style.display = total>0 ? 'flex':'none'; }
function addToBagCart(name,price){ const it = bagCart.find(i=>i.name===name); if(it) it.quantity++; else bagCart.push({name,price,quantity:1}); saveBagCart(); updateBagCartCount(); showNotification(`${name} added to cart`); }
function showNotification(text){ const n = document.createElement('div'); n.className='cart-notification'; n.textContent = `✓ ${text}`; document.body.appendChild(n); setTimeout(()=>n.classList.add('show'),10); setTimeout(()=>{n.classList.remove('show'); setTimeout(()=>n.remove(),300)},1800); }
function setupAddButtons(){ document.querySelectorAll('.product-card').forEach(card=>{ const btn = card.querySelector('.btn-secondary'); if(!btn) return; const title = card.querySelector('h3').textContent; const price = parseFloat(card.querySelector('.price').textContent.replace('$',''))||0; btn.addEventListener('click',()=> addToBagCart(title,price)); }); }
function setupFilters(){ document.querySelectorAll('.filter-btn').forEach(btn=>{ btn.addEventListener('click',()=>{ document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const f = btn.getAttribute('data-filter'); document.querySelectorAll('.product-card').forEach(card=>{ const cat = card.getAttribute('data-category'); card.style.display = (f==='all' || f===cat) ? 'block':'none'; }); }); }); const search = document.querySelector('.search-input'); if(search) search.addEventListener('input',(e)=>{ const v = e.target.value.toLowerCase(); document.querySelectorAll('.product-card').forEach(card=>{ const t = card.querySelector('h3').textContent.toLowerCase(); const d = card.querySelector('.description').textContent.toLowerCase(); card.style.display = (t.includes(v)||d.includes(v))? 'block':'none'; }); }); }
function setupNav(){ const ham = document.querySelector('.hamburger'); const nav = document.querySelector('.nav-links'); if(ham) ham.addEventListener('click',()=>{nav.classList.toggle('active'); ham.classList.toggle('active');}); }
function setupCartIcon(){ const ci = document.querySelector('.cart-icon'); if(!ci) return; ci.addEventListener('click',()=>{ if(bagCart.length===0) return alert('Cart is empty'); let out='Cart:\n\n'; let total=0; bagCart.forEach(i=>{ out+=`${i.name} x${i.quantity} - $${(i.price*i.quantity).toFixed(2)}\n`; total+=i.price*i.quantity; }); out+=`\nTotal: $${total.toFixed(2)}`; alert(out); }); }
function setupScrollTop(){ const s = document.querySelector('.scroll-to-top'); if(!s) return; window.addEventListener('scroll',()=>{ s.style.display = window.pageYOffset>300? 'flex':'none'; }); s.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'})); }
document.addEventListener('DOMContentLoaded',()=>{ loadBagCart(); setupAddButtons(); setupFilters(); setupNav(); setupCartIcon(); setupScrollTop(); });